[package]
name = "rs_todo"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/Sironi-00/rs_todo.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
