[package]
name = "rs_todo"
version = "0.7.0"
edition = "2021"
author = "Sironi-00"
desciption = "A todo app"
repository = "https://github.com/Sironi-00/rs_todo.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
